# Generated by Django 4.1.7 on 2023-03-03 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundHomeUsersAdditionalInfo',
            fields=[
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.soundhomeusers', verbose_name='Autar')),
                ('nickname', models.CharField(blank=True, default='Anonim', max_length=50, unique=True, verbose_name='Name')),
            ],
        ),
    ]
