# Generated by Django 4.1.7 on 2023-03-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundhomeusersadditionalinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auatars/', verbose_name='Auatar'),
        ),
    ]
