# Generated by Django 4.1.7 on 2023-03-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_soundhomeusersadditionalinfo_avtive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soundhomeusersadditionalinfo',
            old_name='avtive',
            new_name='active',
        ),
    ]
