# Generated by Django 4.1.7 on 2023-03-05 13:15

from django.db import migrations, models
import users.components.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_avtive_soundhomeusersadditionalinfo_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundhomeusersadditionalinfo',
            name='nickname',
            field=models.CharField(blank=True, default='anonim', max_length=50, null=True, unique=True, validators=[users.components.validators.UserNicknameValidator.is_valid], verbose_name='Name'),
        ),
    ]
