# Generated by Django 4.1.7 on 2023-03-05 13:16

from django.db import migrations, models
import users.components.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_soundhomeusersadditionalinfo_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundhomeusersadditionalinfo',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='auatars/',
                validators=[
                    users.components.validators.UserAvaValidator.is_valid],
                verbose_name='Auatar'),
        ),
    ]
