# Generated by Django 4.1.7 on 2023-03-07 17:36

from django.db import migrations, models
import users.components.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_soundhomeusersadditionalinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundhomeusersadditionalinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auatars/', validators=[users.components.validators.UserAvaValidator.is_valid], verbose_name='Auatar'),
        ),
        migrations.AlterField(
            model_name='soundhomeusersadditionalinfo',
            name='nickname',
            field=models.CharField(blank=True, default='anonim', max_length=50, null=True, unique=True, validators=[users.components.validators.UserNicknameValidator.is_valid], verbose_name='Name'),
        ),
    ]
