# Generated by Django 4.1.7 on 2023-03-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=50, verbose_name='Album title')),
                ('album_author', models.CharField(max_length=50, verbose_name='Album author')),
                ('album_year', models.CharField(max_length=4, verbose_name='Year of review')),
                ('image_src', models.TextField(max_length=500, verbose_name='Album Image Src')),
                ('album_score', models.CharField(max_length=4, verbose_name='Album Score')),
                ('review_title', models.TextField(max_length=500, verbose_name='Review Title')),
                ('review_text', models.TextField(max_length=10000, verbose_name='Review Text')),
                ('active', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAudio',
            fields=[
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reviews.review')),
                ('name', models.CharField(default='empty_rev', max_length=50)),
                ('audio_review', models.FileField(blank=True, null=True, upload_to='audio_reviews/', verbose_name='Audio Review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTranslation',
            fields=[
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reviews.review')),
                ('translated_review_text', models.TextField(blank=True, max_length=50000, null=True, verbose_name='Translation')),
            ],
        ),
    ]
