# Generated by Django 4.1.7 on 2023-02-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=50)),
                ('album_author', models.CharField(max_length=50)),
                ('album_year', models.CharField(max_length=4)),
                ('image_src', models.TextField(max_length=500)),
                ('album_score', models.CharField(max_length=4)),
                ('review_title', models.TextField(max_length=500)),
                ('review_text', models.TextField(max_length=10000)),
            ],
        ),
    ]
