# Generated by Django 4.1.7 on 2023-02-28 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAudio',
            fields=[
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reviews.review')),
                ('audio_review', models.FileField(blank=True, null=True, upload_to='audio_reviews', verbose_name='Audio Review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTranslation',
            fields=[
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reviews.review')),
                ('translated_review_text', models.TextField(blank=True, max_length=20000, null=True, verbose_name='Translation')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='review',
            name='album_author',
            field=models.CharField(max_length=50, verbose_name='Album author'),
        ),
        migrations.AlterField(
            model_name='review',
            name='album_score',
            field=models.CharField(max_length=4, verbose_name='Album Score'),
        ),
        migrations.AlterField(
            model_name='review',
            name='album_title',
            field=models.CharField(max_length=50, verbose_name='Album title'),
        ),
        migrations.AlterField(
            model_name='review',
            name='album_year',
            field=models.CharField(max_length=4, verbose_name='Year of review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image_src',
            field=models.TextField(max_length=500, verbose_name='Album Image Src'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(max_length=10000, verbose_name='Review Text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_title',
            field=models.TextField(max_length=500, verbose_name='Review Title'),
        ),
    ]
