# Generated by Django 4.1.7 on 2023-03-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_soundhomeusersadditionalinfo_image'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=50, verbose_name='Album title')),
                ('album_author', models.CharField(max_length=50, verbose_name='Album author')),
                ('review_title', models.TextField(max_length=500, verbose_name='Review Title')),
                ('review_text', models.TextField(max_length=10000, verbose_name='Review Text')),
                ('active', models.BooleanField(default=False, verbose_name='Status')),
                ('score', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='users_review_images', verbose_name='AlbumCover')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.soundhomeusers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
