# Generated by Django 4.1.7 on 2023-03-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewaudio_reviewtranslation_review_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtranslation',
            name='translated_review_text',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='Translation'),
        ),
    ]
