# Generated by Django 4.1.7 on 2023-03-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_reviewtranslation_translated_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewaudio',
            name='name',
            field=models.CharField(default='empty_rev', max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewaudio',
            name='audio_review',
            field=models.FileField(blank=True, null=True, upload_to='audio_reviews/', verbose_name='Audio Review'),
        ),
    ]
